<h1>OR Gate ,No hidden layer</h1>

In [49]:
import numpy as np

In [55]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [56]:
def sigmoid(z):
    return 1/(1+(np.exp(-z)))

In [57]:
def derivativeSig(z):
    return sigmoid(z)*(1 - sigmoid(z))

In [58]:
weights = 2*np.random.random((2,1)) - 1
bais = 2*np.random.random((1,1)) - 1
lr = 0.001
weights,bais

(array([[-0.10454337],
        [ 0.09191195]]), array([[-0.11821158]]))

In [59]:
for itter in range(100000):
    output0 = x
    output1 = sigmoid(np.dot(output0,weights) + bais)
#     print(output0.shape)
    
    first_term = output1 - y
    input_of_last_term =  np.dot(output0,weights) + bais
    second_term = derivativeSig(input_of_last_term)
    first_two_term = first_term * second_term
#     print(first_two_term.shape)
    
    changes = np.zeros((2,1))
    
    changes = np.dot(output0.T ,first_two_term)

    weights = weights - lr * changes
    
    bais = bais - np.sum(first_two_term) * lr
    
output1 = sigmoid(np.dot(x,weights) + bais)    
weights,bais,np.around(output1)    
    

(array([[2.61477707],
        [2.61525462]]), array([[-4.04832182]]), array([[0.],
        [0.],
        [0.],
        [1.]]))

In [61]:
t = np.zeros((2,1))
t.shape,t
P = np.dot(output0,weights) + bais
derivativeSig(P)

array([[0.0168581 ],
       [0.15551829],
       [0.15547264],
       [0.17963973]])

In [ ]:
    for i in range(2):
        for j in range(4):
            changes[i][0] += output0[j][i] * first_two_term[j][0]